### ISSUE TITLE
Test workflows started by a message

### ISSUE THREAD

**Issue by pabloromanelli** [zeebe-io/zeebe-test-template-java#2]
Hi, I would like to test a workflow that is started by a message and not a Create Instance command.
Due to that, I don't have an instance of WorkflowInstanceEvent and can't use ZeebeTestRule matchers.

I'm trying to test the result of the workflow filtering records using RecordingExporter but it is much harder.

Do you have any suggestions?

**Comment by saig0** [comment]
Hi @pabloromanelli, this use case is currently not covered by the `ZeebeTestRule`. It depends on the response of the client request. 

However, you can have a look at the Zeebe integration tests. They use the `RecordingExporter` and do assertions with it. For example: https://github.com/zeebe-io/zeebe/blob/develop/engine/src/test/java/io/zeebe/engine/processor/workflow/message/MessageStartEventTest.java#L63-L88

**Comment by pabloromanelli** [comment]
Maybe it could be easier if the method `ZeebeTestRule#assertThat` (and also `WorkflowInstanceAssert#assertThat`, `WorkflowInstanceAssert` constructor) was overloaded to receive a single long value: `workflowInstanceKey`.

Currently I need to mock a fake instance of `WorkflowInstanceEvent` just to use `assertThat`.

This is how I find the instances:
(Kotlin with mockk)
```kotlin
    private fun workflowInstance(userId: String): WorkflowInstanceEvent {
        val workflowInstanceKey = RecordingExporter.variableRecords(CREATED)
                .withName("userId")
                .withValue(""""$userId"""")
                .first.value.workflowInstanceKey
        val workflowInstance = mockk<WorkflowInstanceEvent>()
        every { workflowInstance.workflowInstanceKey } returns workflowInstanceKey
        return workflowInstance
    }
```

Would you like me to create a PR adding an assertThat with `workflowInstanceKey` instead of `WorkflowInstanceEvent`?

**Comment by saig0** [comment]
Nice work :+1: 

I'm not sure if it makes sense to invest more in the `ZeebeTestRule`. I see more potential in a different approach for writing integration tests for Zeebe: 
* running Zeebe in Docker using [Test Containers](https://github.com/zeebe-io/zeebe-test-container)
* collect Zeebe data with [ZeeQS](https://github.com/zeebe-io/zeeqs/)
* building an assertion/verification API on top that consumes from ZeeQS 
* more details here: https://github.com/zeebe-io/zeebe-test-container/issues/6 and https://github.com/zeebe-io/zeebe/issues/3419

**Comment by pabloromanelli** [comment]
Thank you Philipp, I'll have a look to them for integration testing.

Do you know what is the best way to unit test BPMNs?

I want to test if my BPMNs are doing what the product team expected (many little cases, e.g. the user executes this element N times and after that goes to X state).
Currently I'm trying to do this using `ZeebeTestRule` but as you said it is more like an integration test than a unit test: it takes too long to start up and it is impossible to test time (for example, a timer that triggers after 3 days).

For me it would be great to have something like RxJava Schedulers to test time and a fake zeebe broker / client that only models zeebe events to test this cases quickly.

**Comment by saig0** [comment]
Good question. At the moment, there are limit options and experiences for testing Zeebe.

For now, integration tests are the only way to test Zeebe. If the setup is too slow then it might be an option to use the same Zeebe instance for multiple tests. We do something similar for Zeebe's integration tests.

Time-travel is possible in general. The broker has a clock that can be manipulated. Depending on the usage, the clock needs to be exposed.

**Comment by pabloromanelli** [comment]
I just created a pull request to expose the clock in zeebe-test:
https://github.com/zeebe-io/zeebe/pull/4244

I'm closing this issue, thank you for your help Philipp!
