### ISSUE TITLE
tests stuck with  version 0.23.4

### ISSUE THREAD

**Issue by kgignatyev** [zeebe-io/zeebe-test-template-java#4]
I try to run test with latest version of zeebee and tests would not even start

steps to reproduce
in the pom file lets set version
	<version>0.23.4</version>

then run mvn -B clean test| tee log

execution is stuck on 
18:03:32.004 [raft-partition-group-raft-partition-0] INFO  io.atomix.primitive.partition.impl.DefaultPartitionService - Started
18:03:32.005 [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/11]: topology manager
18:03:32.005 [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/11]: metric's server
18:03:32.011 [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/11]: leader management request handler
18:03:32.013 [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/11]: zeebe partitions
18:03:32.014 [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1

environment
java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

the log is attached,
[log.txt](https://github.com/zeebe-io/zeebe-test-template-java/files/4900220/log.txt)

**Comment by kgignatyev** [comment]
after a bit of digging it seems like OSX and jdk12 specific issue related to improperly signed JDK, 

12:04:59.356 [0.0.0.0:25601-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
java.lang.UnsatisfiedLinkError: /private/var/folders/vn/_bctt3k90zdfgz5j524lfykh0000gn/T/librocksdbjni6638134100197319979.jnilib: dlopen(/private/var/folders/vn/_bctt3k90zdfgz5j524lfykh0000gn/T/librocksdbjni6638134100197319979.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/vn/_bctt3k90zdfgz5j524lfykh0000gn/T/librocksdbjni6638134100197319979.jnilib: code signature in (/private/var/folders/vn/_bctt3k90zdfgz5j524lfykh0000gn/T/librocksdbjni6638134100197319979.jnilib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

Switching to jdk14 fixed the problem

**Comment by saig0** [comment]
Thank's for sharing :+1:
